### ISSUE TITLE
[bug] Disable if the project is using an external issue tracker.

### ISSUE THREAD

**Issue by aadrian** [kasancode/gitbucket-label-kanban-plugin#10]
If this plug-in is installed, than **all** GIT repos will have a board, even those that have the issue tracker disabled and configured to an external URL.

**Comment by kasancode** [comment]
What is "Issue tracker"? Redmine? 
I don't use Issue trackers. So I need more information. 

And the New Issue page from Kanban board is different to the default New Issue page, because annotate the issue with the lane (label) or priority etc. 

Is this behavior related to your issue?


**Default New Issue page**
![image](https://user-images.githubusercontent.com/28349574/66397991-ef36bc80-ea17-11e9-9e4b-0732544ba9c9.png)


**from this button**
![image](https://user-images.githubusercontent.com/28349574/66397929-cf9f9400-ea17-11e9-8146-994e60124dd4.png)



**New Issue page with Annotation (different url)**
![image](https://user-images.githubusercontent.com/28349574/66398137-32912b00-ea18-11e9-9752-b901d69a7a29.png)


**from this button**
![image](https://user-images.githubusercontent.com/28349574/66398058-0c6b8b00-ea18-11e9-8dda-55bb5330b56c.png)

**Comment by aadrian** [comment]
> What is "Issue tracker"? Redmine?
> I don't use Issue trackers. So I need more information.

@kasancode 

Your Plug-in displays a Kanban Board of the GitBucket Issues for each GIT project (for all projects) if one installs your plug-in.

GitBucket however has individual project settings that allow to **disable the Issues** (and optionally specify an external URL for some other Issue Trackers like Redmine, Trac, JIRA, etc). 

In this case that project won't have any (internal) issues, so your Kanban Board and Menu Item on the side should be disabled for that project.

**Comment by kasancode** [comment]
I understood.
I'll try to disable the plugin according to the setting.

**Comment by kasancode** [comment]
I investigated the GitBucket codes.

It is difficult to hide the Kanban link in the side menu. 
Perhaps, It is required to modify the GitBucket codes.

However, I can display a Warning if someone visits an invalid Kanban page.

**Comment by aadrian** [comment]
@kasancode 
If a GIT Project has the Internal Issues disabled, than in the table `repository` the column `issues_option` has the value `DISABLE` . In the corresponding model, for that project, the entity `Repository` has the field `issuesOption` for this.

If the GIT Project is using even an **external** Issue Tracker, than in the table `repository` the column `EXTERNAL_ISSUES_URL` also has a non-null value.

**Comment by kasancode** [comment]
Yes, I comfirmed related codes. Therefore we can detect the Internal Issue Tracking is desabled or not.
But, the menu bar displays all plugin items for each repository under any condition.

https://github.com/gitbucket/gitbucket/blob/master/src/main/twirl/gitbucket/core/menu.scala.html#L61

**Comment by aadrian** [comment]
@kasancode the menu display can be configured dynamically from inside a plug-in.

The author of GitBucket explained it here: https://gitter.im/gitbucket/gitbucket_dev?at=5e10a1593062aa3e8df4de7f

**Comment by kasancode** [comment]
Oh, It's working !
Try v3.4.1.

**Comment by aadrian** [comment]
@kasancode this works great! Thank you very much.
